AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'bin/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MultilineOperationIndentation:
   Enabled: true
   EnforcedStyle: indented

GuardClause:
  MinBodyLength: 4

Documentation:
  Enabled: false
